# docker-compose.yml
version: "3.9"

services:
  api:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db]
    volumes:
      - rclone_cfg:/root/.config/rclone

  frontend:
    build: ./frontend
    ports: ["5173:80"]
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cleanmaster
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cleanmaster
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  rclone_cfg:
